/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef SRB2WIN_PRIVATE_H
#define SRB2WIN_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.1.1.1"
#define VER_MAJOR	1
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	1
#define COMPANY_NAME	"Kalaron"
#define FILE_VERSION	"1.01"
#define FILE_DESCRIPTION	"SRB2 - Community Build"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"SRB2CB.exe"
#define PRODUCT_NAME	"SRB2CB"
#define PRODUCT_VERSION	"1.01"

#endif /*SRB2WIN_PRIVATE_H*/
